export enum Role { USER = "USER", CONSULTANT = "CONSULTANT", ADMIN = "ADMIN" }
export enum Seniority { JUNIOR = "JUNIOR", MID = "MID", SENIOR = "SENIOR", LEAD = "LEAD" }
export enum BookingStatus { PENDING = "PENDING", PENDING_PAYMENT = "PENDING_PAYMENT", CONFIRMED = "CONFIRMED", AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION", COMPLETED_RELEASE_PENDING = "COMPLETED_RELEASE_PENDING", COMPLETED = "COMPLETED", CANCELLED = "CANCELLED", DISPUTED = "DISPUTED" }
export enum PaymentStatus { PENDING = "PENDING", PAYMENT_REPORTED = "PAYMENT_REPORTED", PAID_HELD = "PAID_HELD", APPROVED = "APPROVED", HELD = "HELD", TRANSFER_PROCESSING = "TRANSFER_PROCESSING", TRANSFER_FAILED = "TRANSFER_FAILED", RELEASED = "RELEASED", REFUNDED = "REFUNDED", FAILED = "FAILED", DISPUTED = "DISPUTED" }
export enum VerificationStatus { NOT_SUBMITTED = "NOT_SUBMITTED", PENDING = "PENDING", VERIFIED = "VERIFIED", REJECTED = "REJECTED", MORE_INFO_REQUIRED = "MORE_INFO_REQUIRED" }
export enum PrivacyMode { PUBLIC = "PUBLIC", PSEUDONYMOUS = "PSEUDONYMOUS" }
export enum WorkMode { REMOTE = "REMOTE", HYBRID = "HYBRID", ONSITE = "ONSITE" }
