import type { Database, Json } from "@/lib/supabase/database.types";
import { createSupabasePublicClient } from "@/lib/supabase/public";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type ProfileRow = Database["public"]["Views"]["public_profile_cards"]["Row"];
type CompanyRow = Database["public"]["Views"]["public_company_cards"]["Row"];
type ProfessionRow = Database["public"]["Views"]["public_profession_cards"]["Row"];
export type Experience = { id: string; title: string; professionalProfileId?: string; company: { name: string }; profession: { name: string } };
export type PublicReview = { id: string; rating: number; comment: string; user: { name: string } };
export type Availability = { id: string; startsAt: Date; endsAt: Date; isBooked: boolean };
export type PublicProfile = { id: string; headline: string; bio: string; pseudonym: string | null; coverImage: string | null; price30Cents: number; price60Cents: number; responseHours: number; location: string; workMode: string; verificationStatus: string; privacyMode: string; topics: string[]; boundaries: string[]; experiences: Experience[]; reviews: PublicReview[]; availability: Availability[]; user: { name: string; image: string | null }; privacy: { showRealName: boolean; showSurname: boolean; showPhoto: boolean; showCurrentCompany: boolean; showCity: boolean; showExactDates: boolean; showFullHistory: boolean; searchableByCompany: boolean; searchableByProfession: boolean } | null };
export type PublicCompany = Omit<CompanyRow, "id"|"slug"|"name"|"sector"|"description"|"logoText"|"color"|"_count"> & { id:string; slug:string; name:string; sector:string; description:string; logoText:string; color:string; _count:{experiences:number} };
export type PublicProfession = Omit<ProfessionRow, "id"|"slug"|"name"|"category"|"description"|"accent"|"_count"> & { id:string; slug:string; name:string; category:string; description:string; accent:string; _count:{experiences:number} };
export type VerificationDocument = { id: string; originalName: string; sizeBytes: number };
export type DashboardMessage = { id: string; body: string; senderId: string; sender: { name: string }; createdAt: string };
export type DashboardConversation = { id: string; messages: DashboardMessage[] };
export type DashboardBooking = { id: string; status: string; feeCents: number; totalCents: number; startsAt: Date; durationMinutes: number; topics: string[]; goals: string; consultantConfirmedAt: Date | null; consultantRecordingConsent: boolean; meetingUrl: string | null; customer: { name: string }; payment: { status: string; amountCents: number } | null; conversation: DashboardConversation | null };
export type ViewerBooking = DashboardBooking & { professional: PublicProfile; customerConfirmedAt: Date | null; review?: { rating: number; comment: string } | null };
export type ViewerNotification = { id: string; title: string; body: string; href: string | null; readAt: Date | null; createdAt: Date };
export type ViewerDashboard = { id: string; name: string; customerBookings: ViewerBooking[]; favorites: { id: string; professionalProfile: PublicProfile }[]; notifications: ViewerNotification[] };
export type ConsultantNotification = { id: string; title: string; body: string; href: string | null; readAt: Date | null; createdAt: Date };
export type ConsultantDashboard = { id: string; headline: string; bio: string; publicSurname: string | null; coverImage: string | null; location: string; region: string; workMode: string; seniority: string; yearsExperience: number; price30Cents: number; price60Cents: number; responseHours: number; topics: string[]; boundaries: string[]; experiences: Array<{ companyId: string; professionId: string; title: string }>; user: { name: string; image: string | null }; privacy: { showRealName: boolean; showSurname: boolean; showPhoto: boolean; showCurrentCompany: boolean; showCity: boolean; showExactDates: boolean; showFullHistory: boolean; searchableByCompany: boolean; searchableByProfession: boolean } | null; bookings: DashboardBooking[]; notifications: ConsultantNotification[]; availability: Availability[]; profileViews: { id: string }[]; favorites: { id: string }[]; verificationStatus: string };
export type Paginated<T> = { items:T[]; total:number; page:number; pageSize:number };

const object = (value: Json | undefined): Record<string, Json | undefined> => value !== null && typeof value === "object" && !Array.isArray(value) ? value : {};
const array = (value: Json | undefined): Json[] => Array.isArray(value) ? value : [];
const string = (value: Json | undefined, fallback="") => typeof value === "string" ? value : fallback;
const number = (value: Json | undefined) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const boolean = (value: Json | undefined) => typeof value === "boolean" ? value : false;
const date = (value: Json | undefined) => new Date(string(value));

function profile(row: ProfileRow): PublicProfile {
  const user=object(row.user ?? undefined); const privacy=row.privacy === null ? null : object(row.privacy);
  return { id:row.id??"", headline:row.headline??"", bio:row.bio??"", pseudonym:row.pseudonym, coverImage:null, price30Cents:row.price30Cents??0, price60Cents:row.price60Cents??0, responseHours:row.responseHours??0, location:row.location??"", workMode:row.workMode??"REMOTE", verificationStatus:row.verificationStatus??"NOT_SUBMITTED", privacyMode:row.privacyMode??"PROTECTED", topics:row.topics??[], boundaries:row.boundaries??[], user:{name:string(user.name,"Profissional"),image:typeof user.image==="string"?user.image:null}, privacy:privacy?{showRealName:boolean(privacy.showRealName),showSurname:boolean(privacy.showSurname),showPhoto:boolean(privacy.showPhoto),showCurrentCompany:boolean(privacy.showCurrentCompany),showCity:boolean(privacy.showCity),showExactDates:boolean(privacy.showExactDates),showFullHistory:boolean(privacy.showFullHistory),searchableByCompany:boolean(privacy.searchableByCompany),searchableByProfession:boolean(privacy.searchableByProfession)}:null,
    experiences:array(row.experiences??undefined).map((item,i)=>{const x=object(item);return{id:string(x.id,`experience-${i}`),title:string(x.title),company:{name:string(object(x.company).name,"Empresa não informada")},profession:{name:string(object(x.profession).name,"Profissão não informada")}}}),
    reviews:array(row.reviews??undefined).map((item,i)=>{const x=object(item);return{id:string(x.id,`review-${i}`),rating:number(x.rating),comment:string(x.comment),user:{name:string(object(x.user).name,"Cliente")}}}),
    availability:array(row.availability??undefined).map(item=>{const x=object(item);return{id:string(x.id),startsAt:date(x.startsAt),endsAt:date(x.endsAt),isBooked:boolean(x.isBooked)}}).filter(x=>x.id&&!Number.isNaN(x.startsAt.getTime())&&!Number.isNaN(x.endsAt.getTime())) };
}
const count=(x:Json|null)=>number(object(x??undefined).experiences);
const company=(x:CompanyRow):PublicCompany=>({...x,id:x.id??"",slug:x.slug??"",name:x.name??"",sector:x.sector??"",description:x.description??"",logoText:x.logoText??"",color:x.color??"var(--blue)",_count:{experiences:count(x._count)}});
const profession=(x:ProfessionRow):PublicProfession=>({...x,id:x.id??"",slug:x.slug??"",name:x.name??"",category:x.category??"",description:x.description??"",accent:x.accent??"var(--mineral)",_count:{experiences:count(x._count)}});

export async function getHomeData(){const s=createSupabasePublicClient();const [m,p,c,r]=await Promise.all([s.from("home_metrics").select("*").single(),s.from("public_profile_cards").select("*").limit(8),s.from("public_company_cards").select("*").limit(8),s.from("public_profession_cards").select("*").limit(6)]);const e=m.error??p.error??c.error??r.error;if(e||!m.data)throw new Error(e?.message??"Métricas indisponíveis");return{professionalCount:Number(m.data.active_professionals),companyCount:Number(m.data.represented_companies),completedCount:Number(m.data.completed_conversations),rating:Number(m.data.average_rating),professionals:(p.data??[]).map(profile),companies:(c.data??[]).map(company),professions:(r.data??[]).map(profession)}}
export async function getPublicCompanies(){const{data,error}=await createSupabasePublicClient().from("public_company_cards").select("*").order("name");if(error)throw new Error(error.message);return(data??[]).map(company)}
export async function getPublicProfessions(){const{data,error}=await createSupabasePublicClient().from("public_profession_cards").select("*").order("name");if(error)throw new Error(error.message);return(data??[]).map(profession)}
export async function getPublicCompaniesPage(page=1){const size=25,from=(Math.max(1,page)-1)*size;const{data,count:total,error}=await createSupabasePublicClient().from("public_company_cards").select("*",{count:"exact"}).order("name").range(from,from+size-1);if(error)throw new Error(error.message);return{items:(data??[]).map(company),total:total??0,page,pageSize:size}}
export async function getPublicProfessionsPage(page=1){const size=25,from=(Math.max(1,page)-1)*size;const{data,count:total,error}=await createSupabasePublicClient().from("public_profession_cards").select("*",{count:"exact"}).order("name").range(from,from+size-1);if(error)throw new Error(error.message);return{items:(data??[]).map(profession),total:total??0,page,pageSize:size}}
export async function getPublicRealityChecks(){const{data,error}=await createSupabasePublicClient().from("RealityCheck").select("*, profession:Profession(*)");if(error)throw new Error(error.message);return data??[]}
export async function searchProfessionalsPage(params:{q?:string;company?:string;profession?:string;mode?:string;location?:string;page?:number}):Promise<Paginated<PublicProfile>>{const page=Math.max(1,params.page??1),pageSize=24;const{data,error}=await createSupabasePublicClient().rpc("search_public_profiles",{p_query:params.q?.trim()||undefined,p_company_slug:params.company||undefined,p_profession_slug:params.profession||undefined,p_work_mode:params.mode||undefined,p_location:params.location?.trim()||undefined,p_limit:pageSize,p_offset:(page-1)*pageSize});if(error)throw new Error(`Supabase search failed: ${error.message}`);const rows=Array.isArray(data)?data:[];return{items:rows.map(item=>profileFromJson(object(item).profile)).filter(x=>x.id),total:rows.length?number(object(rows[0]).total_count):0,page,pageSize}}
function profileFromJson(value:Json|undefined):PublicProfile{const x=object(value);return profile({id:string(x.id),headline:string(x.headline),bio:string(x.bio),pseudonym:typeof x.pseudonym==="string"?x.pseudonym:null,price30Cents:number(x.price30Cents),price60Cents:number(x.price60Cents),responseHours:number(x.responseHours),location:string(x.location),region:string(x.region),workMode:string(x.workMode) as Database["public"]["Enums"]["WorkMode"],verificationStatus:string(x.verificationStatus) as Database["public"]["Enums"]["VerificationStatus"],privacyMode:string(x.privacyMode) as Database["public"]["Enums"]["PrivacyMode"],seniority:string(x.seniority) as Database["public"]["Enums"]["Seniority"],yearsExperience:number(x.yearsExperience),topics:array(x.topics).map(v=>string(v)),boundaries:array(x.boundaries).map(v=>string(v)),experiences:x.experiences??null,reviews:x.reviews??null,availability:x.availability??null,user:x.user??null,privacy:x.privacy??null})}
export async function searchProfessionals(params:{q?:string;company?:string;profession?:string;mode?:string;location?:string}){return(await searchProfessionalsPage(params)).items}
export async function getProfessional(id:string){const s=createSupabasePublicClient();const[{data,error},{data:cover,error:coverError}]=await Promise.all([s.from("public_profile_cards").select("*").eq("id",id).maybeSingle(),s.from("ProfileCover").select("image").eq("professionalProfileId",id).maybeSingle()]);if(error)throw new Error(error.message);if(coverError)throw new Error(coverError.message);if(!data)return null;const result=profile(data);return {...result,coverImage:result.privacy?.showPhoto?(cover?.image??null):null}}
export async function getViewerDashboard(userId:string):Promise<ViewerDashboard|null>{const{data,error}=await(await createSupabaseServerClient()).rpc("get_viewer_dashboard",{p_user_id:userId});if(error)throw new Error(error.message);return data?parseViewer(data):null}
export async function getConsultantDashboard(userId:string):Promise<ConsultantDashboard|null>{const s=await createSupabaseServerClient();const{data,error}=await s.rpc("get_consultant_dashboard",{p_user_id:userId});if(error)throw new Error(error.message);if(!data)return null;const profileId=string(object(data).id);const{data:cover,error:coverError}=await s.from("ProfileCover").select("image").eq("professionalProfileId",profileId).maybeSingle();if(coverError)throw new Error(coverError.message);return parseConsultant({...object(data),coverImage:cover?.image??null} as Json)}
function parseConsultant(value:Json):ConsultantDashboard{const x=object(value);return{id:string(x.id),headline:string(x.headline),bio:string(x.bio),publicSurname:typeof x.publicSurname==="string"?x.publicSurname:null,coverImage:typeof x.coverImage==="string"?x.coverImage:null,location:string(x.location),region:string(x.region),workMode:string(x.workMode),seniority:string(x.seniority),yearsExperience:number(x.yearsExperience),price30Cents:number(x.price30Cents),price60Cents:number(x.price60Cents),responseHours:number(x.responseHours),topics:array(x.topics).map(v=>string(v)),boundaries:array(x.boundaries).map(v=>string(v)),experiences:array(x.experiences).map(v=>{const y=object(v);return{companyId:string(y.companyId),professionId:string(y.professionId),title:string(y.title)}}),user:{name:string(object(x.user).name),image:typeof object(x.user).image==="string"?string(object(x.user).image):null},privacy:parsePrivacy(x.privacy),bookings:array(x.bookings).map(parseBooking),notifications:array(x.notifications).map(v=>{const y=object(v);return{id:string(y.id),title:string(y.title),body:string(y.body),href:typeof y.href==="string"?string(y.href):null,readAt:y.readAt?date(y.readAt):null,createdAt:date(y.createdAt)}}),availability:array(x.availability).map(v=>{const y=object(v);return{id:string(y.id),startsAt:date(y.startsAt),endsAt:date(y.endsAt),isBooked:boolean(y.isBooked)}}),profileViews:array(x.profileViews).map(v=>({id:string(object(v).id)})),favorites:array(x.favorites).map(v=>({id:string(object(v).id)})),verificationStatus:string(x.verificationStatus)}}
function parsePrivacy(v:Json|undefined):ConsultantDashboard["privacy"]{if(v==null)return null;const x=object(v);return{showRealName:boolean(x.showRealName),showSurname:boolean(x.showSurname),showPhoto:boolean(x.showPhoto),showCurrentCompany:boolean(x.showCurrentCompany),showCity:boolean(x.showCity),showExactDates:boolean(x.showExactDates),showFullHistory:boolean(x.showFullHistory),searchableByCompany:boolean(x.searchableByCompany),searchableByProfession:boolean(x.searchableByProfession)}}
function parseBooking(v:Json):DashboardBooking{const x=object(v),p=x.payment?object(x.payment):null,c=x.conversation?object(x.conversation):null;return{id:string(x.id),status:string(x.status),feeCents:number(x.feeCents),totalCents:number(x.totalCents),startsAt:date(x.startsAt),durationMinutes:number(x.durationMinutes),topics:array(x.topics).map(y=>string(y)),goals:string(x.goals),consultantConfirmedAt:x.consultantConfirmedAt?date(x.consultantConfirmedAt):null,consultantRecordingConsent:boolean(x.consultantRecordingConsent),meetingUrl:typeof x.meetingUrl==="string"?x.meetingUrl:null,customer:{name:string(object(x.customer).name)},payment:p?{status:string(p.status),amountCents:number(p.amountCents)}:null,conversation:c?{id:string(c.id),messages:array(c.messages).map(m=>{const y=object(m);return{id:string(y.id),body:string(y.body),senderId:string(y.senderId),sender:{name:string(object(y.sender).name)},createdAt:string(y.createdAt)}})}:null}}
function parseViewer(v:Json):ViewerDashboard{const x=object(v);return{id:string(x.id),name:string(x.name),customerBookings:array(x.customerBookings).map(item=>{const y=object(item);return{...parseBooking(item),customerConfirmedAt:y.customerConfirmedAt?date(y.customerConfirmedAt):null,professional:profileFromJson(y.professional),review:y.review?{rating:number(object(y.review).rating),comment:string(object(y.review).comment)}:null}}),favorites:array(x.favorites).map(item=>{const y=object(item);return{id:string(y.id),professionalProfile:profileFromJson(y.professionalProfile)}}),notifications:array(x.notifications).map(item=>{const y=object(item);return{id:string(y.id),title:string(y.title),body:string(y.body),href:typeof y.href==="string"?y.href:null,readAt:y.readAt?date(y.readAt):null,createdAt:date(y.createdAt)}})}}
export async function getAdminData(){const s=await createSupabaseServerClient();const[u,p,b,v,r,m,usersList]=await Promise.all([s.from("User").select("id",{count:"exact",head:true}),s.from("ProfessionalProfile").select("id",{count:"exact",head:true}),s.from("Booking").select("id",{count:"exact",head:true}),s.from("Verification").select("*, documents:VerificationDocument(*), professionalProfile:ProfessionalProfile(*, user:User(name), experiences:EmploymentExperience(*, company:Company(name)))").eq("status","PENDING"),s.from("Report").select("*"),s.from("Payment").select("status, amountCents"),s.from("User").select("id, name, email, role, onboardingCompleted, twoFactorEnabled, createdAt").order("createdAt",{ascending:false}).limit(100)]);const e=u.error??p.error??b.error??v.error??r.error??m.error??usersList.error;if(e)throw new Error(e.message);const reports=r.data??[];return{users:u.count??0,professionals:p.count??0,bookings:b.count??0,pending:v.data??[],reports,supportReports:reports.filter(report=>!report.bookingId&&!report.targetUserId),usersList:usersList.data??[],revenueCents:(m.data??[]).filter(x=>x.status==="PAID_HELD"||x.status==="RELEASED").reduce((sum,x)=>sum+x.amountCents,0)}}
export async function getCompanyBySlug(slug:string){const{data,error}=await createSupabasePublicClient().from("public_company_details").select("*").eq("slug",slug).maybeSingle();if(error)throw new Error(error.message);return data}
export async function getProfessionBySlug(slug:string){const{data,error}=await createSupabasePublicClient().from("public_profession_details").select("*").eq("slug",slug).maybeSingle();if(error)throw new Error(error.message);return data}
export async function getRealityCheckBySlug(slug:string){const{data,error}=await createSupabasePublicClient().from("RealityCheck").select("*, profession:Profession!inner(*)").eq("profession.slug",slug).maybeSingle();if(error)throw new Error(error.message);return data?{...data,imagined:data.imagined??[],practical:data.practical??[]}:null}
export async function getUserById(id:string){const{data,error}=await(await createSupabaseServerClient()).from("User").select("*, professionalProfile:ProfessionalProfile(*)").eq("id",id).maybeSingle();if(error)throw new Error(error.message);return data}
export async function getBookingForUser(id:string,userId:string){const{data,error}=await(await createSupabaseServerClient()).from("Booking").select("*, professional:ProfessionalProfile(*, user:User(*)), payment:Payment(*)").eq("id",id).eq("customerId",userId).maybeSingle();if(error)throw new Error(error.message);return data?{...data,payment:data.payment[0]??null}:null}
export function getProfessionalInclude(){return{}}
