import { notFound } from "next/navigation";
import { payBookingAction } from "@/app/actions";
import { PublicShell } from "@/components/public-shell";
import { money, shortDate } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/session";
export const dynamic="force-dynamic";
export default async function CheckoutPage({params}:{params:Promise<{id:string}>}){const user=await requireUser();const {id}=await params;const booking=await prisma.booking.findFirst({where:{id,customerId:user.id},include:{professional:{include:{user:true}},payment:true}});if(!booking)notFound();return <PublicShell><section className="page-hero" data-mark="R$"><div className="container page-hero-inner"><span className="eyebrow">Checkout demonstrativo</span><h1>Confirme o encontro.</h1><p>Nenhum cartão real será cobrado neste MVP.</p></div></section><section className="section"><div className="container profile-layout"><div className="panel"><span className="eyebrow">Resumo</span><ul className="detail-list"><li><span>Profissional</span><strong>{booking.professional.user.name}</strong></li><li><span>Data</span><strong>{shortDate(booking.startsAt)}</strong></li><li><span>Duração</span><strong>{booking.durationMinutes} min</strong></li><li><span>Conversa</span><strong>{money(booking.subtotalCents)}</strong></li><li><span>Taxa da plataforma</span><strong>{money(booking.feeCents)}</strong></li><li><span>Total</span><strong>{money(booking.totalCents)}</strong></li></ul></div><aside className="booking-box"><span className="eyebrow">Ambiente acadêmico</span><h2>Pagamento simulado</h2><p>Ao confirmar, o registro de pagamento muda para aprovado, a consulta é confirmada e uma notificação é criada.</p>{booking.status === "PENDING_PAYMENT" ? <form action={payBookingAction.bind(null,booking.id)}><button className="button button-accent button-block" type="submit">Simular pagamento e confirmar</button></form> : <p className="status">Consulta {booking.status.toLowerCase()}</p>}</aside></div></section></PublicShell>}

