import { PublicShell } from "@/components/public-shell";

const sections = [
  ["1. O que ? a Insidely", "A Insidely aproxima pessoas que esto pesquisando uma carreira ou empresa de profissionais que aceitam compartilhar experis. A plataforma n representa empresas citadas e n garante contrata, sal, promo ou resultado profissional."],
  ["2. Conta e informa", "Para criar uma conta, o usu?rio deve informar nome, e-mail v?lido e senha. Quem compartilhar experis profissionais tamb deve concluir o perfil profissional com dados verdadeiros e manter as informa atualizadas."],
  ["3. Conversas e pagamentos", "Conversas s agendadas e pagas dentro da plataforma. O valor pode permanecer retido at a conversa ser confirmada pelos participantes ou at o prazo de seguran terminar sem contesta. N ? permitido usar perfil, mensagens ou descri p para desviar pagamento, divulgar contato pessoal ou negociar a conversa fora da Insidely."],
  ["4. Privacidade e conduta", "N compartilhe segredos de empresa, dados pessoais de terceiros, informa internas confidenciais, senhas ou material protegido. O consultor decide o que fica p; documentos de verifica n aparecem no perfil."],
  ["5. Grava, confirma e suporte", "Uma conversa s? pode ser gravada quando os dois participantes aceitarem expressamente. Registros de presen?a e dura podem ser usados para suporte e an de contesta. Depois do encontro, ambos podem confirmar a realiza; se houver contesta, o valor fica retido at an. Den?ncias e pedidos de suporte s avaliados pela plataforma."],
  ["6. Suspens e encerramento", "A Insidely pode restringir ou encerrar contas que forne?am dados falsos, tentem burlar pagamento, pratiquem ass?dio, violem privacidade ou descumpram estes termos. O usu?rio tamb pode pedir a exclus da pr conta pela  de configura."],
];

export default function TermsPage(){return <PublicShell><section className="page-hero" data-mark="?"><div className="container page-hero-inner"><span className="eyebrow">Termos de Uso ? vers 2026-08</span><h1>Regras claras para conversas mais seguras.</h1><p>Leia antes de criar uma conta, agendar uma conversa ou publicar uma experi profissional.</p></div></section><section className="section"><article className="container legal-copy">{sections.map(([title,copy])=><section key={title}><h2>{title}</h2><p>{copy}</p></section>)}<p className="muted">?ltima atualiza: agosto de 2026.</p></article></section></PublicShell>}
