"use client";
import Link from "next/link";
import { useActionState } from "react";
import { loginAction, registerAction } from "@/app/actions";

function SocialButtons({ google, linkedin }: { google: boolean; linkedin: boolean }) { if (!google && !linkedin) return null; return <><div className="auth-divider"><span>ou continue com</span></div><div className="social-grid">{google && <Link className="button social-button button-block" href="/auth/google?next=/continuar"><strong>G</strong> Entrar com Google</Link>}{linkedin && <a className="button social-button button-block" href="/api/auth/signin/linkedin"><strong>in</strong> Entrar com LinkedIn</a>}</div></>; }

export function LoginForm({ google, linkedin, socialPending = false }: { google: boolean; linkedin: boolean; socialPending?: boolean }) { const [error, action, pending] = useActionState(loginAction, undefined); return <form action={action} className="auth-form form-stack"><span className="eyebrow">Acesso seguro</span><h2>Entre na sua conta.</h2>{(error || socialPending) && <p className="form-error" role="alert">{error || "O login social n p ser conclu?do. Tente novamente."}</p>}<div className="field"><label htmlFor="email">E-mail</label><input className="input" id="email" name="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="password">Senha</label><input className="input" id="password" name="password" type="password" autoComplete="current-password" minLength={8} required/></div><button className="button button-accent button-block" disabled={pending}>{pending ? "Entrando." : "Entrar"}</button><SocialButtons google={google} linkedin={linkedin}/><p>N conta? <Link href="/cadastro"><u>Cadastre-se</u></Link></p><div className="demo-box"><strong>Acessos demonstrativos</strong><br/>Usu?rio: demo@insidely.com<br/>Consultor: consultor@insidely.com<br/>Admin: admin@insidely.com<br/>Senha: Demo@123</div></form>; }

export function RegisterForm({ google, linkedin }: { google: boolean; linkedin: boolean }) { const [error, action, pending] = useActionState(registerAction, undefined); return <form action={action} className="auth-form form-stack"><span className="eyebrow">Comece por aqui</span><h2>Crie sua conta.</h2>{error && <p className="form-error" role="alert">{error}</p>}<div className="field"><label htmlFor="name">Nome</label><input className="input" id="name" name="name" autoComplete="name" required/></div><div className="field"><label htmlFor="email">E-mail</label><input className="input" id="email" name="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="password">Senha</label><input className="input" id="password" name="password" type="password" autoComplete="new-password" minLength={8} required/><small>Use ao menos 8 caracteres, uma mai</small></div><div className="field"><label htmlFor="confirmPassword">Confirmar senha</label><input className="input" id="confirmPassword" name="confirmPassword" type="password" autoComplete="new-password" minLength={8} required/></div><div className="field"><label htmlFor="role">Quero</label><select className="select" id="role" name="role"><option value="USER">Conversar com profissionais</option><option value="CONSULTANT">Compartilhar minha experi</option></select></div><label className="check-row"><input name="terms" type="checkbox" required/><span>Li e concordo com os <Link href="/termos" target="_blank"><u>Termos de Uso</u></Link> e a <Link href="/privacidade" target="_blank"><u>Pol de Privacidade</u></Link>.</span></label><button className="button button-accent button-block" disabled={pending}>{pending ? "Criando." : "Criar conta"}</button><SocialButtons google={google} linkedin={linkedin}/><p>J conta? <Link href="/entrar"><u>Entrar</u></Link></p></form>; }
