"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { loginAction, registerAction, requestPasswordResetAction, socialSignInAction, updatePasswordAction } from "@/app/actions";
function PasswordField({name,label,autoComplete}:{name:string;label:string;autoComplete?:string}){const [visible,setVisible]=useState(false);return <label>{label}<span className="password-field"><input className="input" name={name} type={visible?"text":"password"} autoComplete={autoComplete} minLength={8} required/><button type="button" className="password-toggle" onClick={()=>setVisible(v=>!v)}>{visible?"Ocultar":"Mostrar"}</button></span></label>}
function SocialButtons({google,linkedin}:{google:boolean;linkedin:boolean}){if(!google&&!linkedin)return null;return <div className="social-grid">{google&&<Link className="button social-button" href="/auth/google?next=/continuar">Google</Link>}{linkedin&&<button className="button social-button" type="submit" formAction={socialSignInAction.bind(null,"linkedin_oidc")}>LinkedIn</button>}</div>}
export function LoginForm({google,linkedin,socialPending=false}:{google:boolean;linkedin:boolean;socialPending?:boolean}){const [error,action,pending]=useActionState(loginAction,undefined);return <form action={action} className="auth-form form-stack"><span className="eyebrow">Acesso seguro</span><h2>Entre na sua conta.</h2>{(error||socialPending)&&<p className="form-error" role="alert">{error||"Não foi possível concluir o login social."}</p>}<label>E-mail<input className="input" name="email" type="email" required/></label><PasswordField name="password" label="Senha" autoComplete="current-password"/><button className="button button-accent button-block" disabled={pending}>{pending?"Entrando...":"Entrar"}</button><Link href="/recuperar-senha"><u>Esqueci minha senha</u></Link><SocialButtons google={google} linkedin={linkedin}/><p>Não tem uma conta? <Link href="/cadastro"><u>Cadastre-se</u></Link></p></form>}
export function RegisterForm({google,linkedin}:{google:boolean;linkedin:boolean}){const [error,action,pending]=useActionState(registerAction,undefined);return <form action={action} className="auth-form form-stack"><h2>Crie sua conta.</h2>{error&&<p className="form-error" role="alert">{error}</p>}<label>Nome<input className="input" name="name" required/></label><label>E-mail<input className="input" name="email" type="email" required/></label><PasswordField name="password" label="Senha" autoComplete="new-password"/><PasswordField name="confirmPassword" label="Confirmar senha" autoComplete="new-password"/><select className="select" name="role"><option value="USER">Conversar com profissionais</option><option value="CONSULTANT">Compartilhar minha experiência</option></select><label className="check-row"><input name="terms" type="checkbox" required/><span>Li e concordo com os termos.</span></label><button className="button button-accent button-block" disabled={pending}>{pending?"Criando...":"Criar conta"}</button><SocialButtons google={google} linkedin={linkedin}/></form>}
export function PasswordRecoveryForm(){const [message,action,pending]=useActionState(requestPasswordResetAction,undefined);return <form action={action} className="auth-form form-stack"><h2>Esqueceu sua senha?</h2>{message&&<p className="form-feedback" role="status">{message}</p>}<label>E-mail<input className="input" name="email" type="email" required/></label><button className="button button-accent button-block" disabled={pending}>{pending?"Enviando…":"Enviar link"}</button><Link href="/entrar">Voltar para entrar</Link></form>}
export function NewPasswordForm(){const [message,action,pending]=useActionState(updatePasswordAction,undefined);return <form action={action} className="auth-form form-stack"><h2>Crie uma nova senha.</h2>{message&&<p className="form-error" role="alert">{message}</p>}<label>Nova senha<input className="input" name="password" type="password" minLength={8} required/></label><label>Confirmar senha<input className="input" name="confirmation" type="password" minLength={8} required/></label><button className="button button-accent button-block" disabled={pending}>Alterar senha</button></form>}
