"use client";

import { Camera, Trash2, Upload } from "lucide-react";
import { useActionState, useState } from "react";
import { deleteAccountAction, submitVerificationAction, updateProfessionalProfileAction, updateProfileImageAction } from "@/app/actions";

export function ProfileImageForm({ image, name }: { image?: string | null; name: string }) {
  const [message, action, pending] = useActionState(updateProfileImageAction, undefined);
  const [preview, setPreview] = useState(image ?? "");
  return <section className="panel profile-photo-panel"><div className="profile-photo-heading"><label className="profile-photo" htmlFor="profile-image" style={preview ? { backgroundImage: `url(${preview})` } : undefined}>{preview ? null : name.slice(0, 1).toUpperCase()}<Camera size={18}/></label><div><span className="eyebrow">Foto de perfil</span><h2>Mostre quem está por trás da experiência.</h2></div></div><form className="upload-row" action={action}><input className="file-input" id="profile-image" name="image" type="file" accept="image/png,image/jpeg,image/webp" required onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) setPreview(URL.createObjectURL(file)); }}/><label className="button button-ghost" htmlFor="profile-image"><Upload size={16}/> Escolher foto</label><button className="button button-dark" disabled={pending}>{pending ? "Enviando…" : "Salvar foto"}</button></form>{message && <p className="form-feedback" role="status">{message}</p>}<p className="muted">JPG, PNG ou WEBP de até 3 MB. Clique na foto para escolher outra imagem.</p></section>;
}

export function VerificationRequestForm() {
  const [message, action, pending] = useActionState(submitVerificationAction, undefined);
  return <form className="verification-form" action={action}>
    <div className="field"><label htmlFor="method">Como voc</label><select className="select" id="method" name="method" defaultValue="employment_document"><option value="company_email">E-mail corporativo</option><option value="employment_document">Documento de v profissional</option><option value="professional_reference">Refer profissional verific?vel</option></select></div>
    <div className="field"><label htmlFor="document">Comprovante privado</label><input className="file-control" id="document" name="document" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" required/><small>PDF, JPG, PNG ou WEBP de at 5 MB.</small></div>
    <div className="verification-note"><Upload size={18}/><span>O arquivo fica privado e  No perfil p aparece apenas o resultado da verifica.</span></div>
    {message && <p className="form-feedback" role="status">{message}</p>}
    <button className="button button-accent" type="submit" disabled={pending}>{pending ? "Enviando com seguran." : "Enviar para verifica"}</button>
  </form>;
}

type SelectOption = { id: string; name: string; category?: string };
type ProfessionalProfileValues = { headline: string; bio: string; location: string; region: string; workMode: string; seniority: string; yearsExperience: number; price30Cents: number; price60Cents: number; responseHours: number; pixKey?: string | null; topics: string[]; boundaries: string[]; experiences: Array<{ companyId: string; professionId: string; title: string }> };

export function ProfessionalProfileForm({ profile, companies, professions }: { profile: ProfessionalProfileValues; companies: SelectOption[]; professions: SelectOption[] }) {
  const [message, action, pending] = useActionState(updateProfessionalProfileAction, undefined);
  const experience = profile.experiences[0];
  return <section className="panel professional-edit-panel"><span className="eyebrow">Perfil p de consultor</span><h2>O que as pessoas poder conhecer sobre sua experi.</h2><p className="muted">Esta  ? diferente da conta de quem agenda conversas. Informa confidenciais n devem ser inclu.</p><form action={action} className="form-stack" style={{marginTop:22}}>
    <div className="field"><label htmlFor="headline">T profissional</label><input className="input" id="headline" name="headline" defaultValue={profile.headline} minLength={5} required/></div>
    <div className="field"><label htmlFor="bio">Apresenta</label><textarea className="textarea" id="bio" name="bio" defaultValue={profile.bio} minLength={30} required/></div>
    <div className="profile-form-grid"><div className="field"><label htmlFor="title">Cargo</label><input className="input" id="title" name="title" defaultValue={experience?.title ?? ""} minLength={2} required/></div><div className="field"><label htmlFor="companyId">Empresa ou experi</label><select className="select" id="companyId" name="companyId" defaultValue={experience?.companyId ?? ""} required><option value="" disabled>Selecione</option>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select></div><div className="field"><label htmlFor="professionId"> de atua</label><select className="select" id="professionId" name="professionId" defaultValue={experience?.professionId ?? ""} required><option value="" disabled>Selecione</option>{professions.map(profession=><option key={profession.id} value={profession.id}>{profession.name}</option>)}</select></div><div className="field"><label htmlFor="yearsExperience">Anos de experi</label><input className="input" id="yearsExperience" name="yearsExperience" type="number" min="0" max="60" defaultValue={profile.yearsExperience} required/></div></div>
    <div className="profile-form-grid"><div className="field"><label htmlFor="location">Cidade/UF</label><input className="input" id="location" name="location" defaultValue={profile.location} required/></div><div className="field"><label htmlFor="region">Pa</label><input className="input" id="region" name="region" defaultValue={profile.region} required/></div><div className="field"><label htmlFor="workMode">Modelo de trabalho</label><select className="select" id="workMode" name="workMode" defaultValue={profile.workMode}><option value="REMOTE">Remoto</option><option value="HYBRID">H</option><option value="ONSITE">Presencial</option></select></div><div className="field"><label htmlFor="seniority">N</label><select className="select" id="seniority" name="seniority" defaultValue={profile.seniority}><option value="INTERN">Est</option><option value="JUNIOR">J</option><option value="MID">Pleno</option><option value="SENIOR">S</option><option value="LEAD">Lideran</option><option value="MANAGER">Gest</option></select></div></div>
    <div className="profile-form-grid"><div className="field"><label htmlFor="price30Cents">Valor por 30 min (R$ em centavos)</label><input className="input" id="price30Cents" name="price30Cents" type="number" min="1000" step="100" defaultValue={profile.price30Cents} required/><small>Ex.: R$ 45,00 = 4500.</small></div><div className="field"><label htmlFor="price60Cents">Valor por 60 min (R$ em centavos)</label><input className="input" id="price60Cents" name="price60Cents" type="number" min="1000" step="100" defaultValue={profile.price60Cents} required/><small>Ex.: R$ 80,00 = 8000.</small></div><div className="field"><label htmlFor="responseHours">Prazo de resposta (horas)</label><input className="input" id="responseHours" name="responseHours" type="number" min="1" max="168" defaultValue={profile.responseHours} required/></div></div>
    <div className="field"><label htmlFor="pixKey">Chave Pix para receber repasses</label><input className="input" id="pixKey" name="pixKey" defaultValue={profile.pixKey ?? ""} placeholder="CPF, e-mail, telefone ou chave aleat"/><small>Ficar privada. Na vers final, o provedor marketplace faz o repasse somente ap a confirma da conversa.</small></div>
    <div className="field"><label htmlFor="topics">Temas que voc conversar</label><input className="input" id="topics" name="topics" defaultValue={profile.topics.join(", ")} required/><small>Separe os temas por v.</small></div>
    <div className="field"><label htmlFor="boundaries">Limites da conversa</label><input className="input" id="boundaries" name="boundaries" defaultValue={profile.boundaries.join(", ")} required/><small>Ex.: dados confidenciais, informa de terceiros.</small></div>
    {message && <p className="form-feedback" role="status">{message}</p>}<button className="button button-dark" type="submit" disabled={pending}>{pending ? "Salvando." : "Salvar perfil profissional"}</button>
  </form></section>;
}

export function AccountDangerZone({ email }: { email: string }) {
  return <section className="panel danger-zone"><span className="eyebrow">Controle da conta</span><h2>Excluir minha conta</h2><p>Esta a remove seu perfil e os dados vinculados. Para confirmar, digite seu e-mail completo.</p><form action={deleteAccountAction} className="form-stack"><div className="field"><label htmlFor="confirmation">Confirme com {email}</label><input className="input" id="confirmation" name="confirmation" type="email" autoComplete="off" required/></div><button className="button danger-button" type="submit"><Trash2 size={16}/> Excluir conta definitivamente</button></form></section>;
}
