import Link from "next/link";
import { Role, VerificationStatus } from "@prisma/client";
import { ArrowUpRight, BadgeCheck, Building2, CircleAlert, Clock3, ShieldCheck } from "lucide-react";
import { submitVerificationAction } from "@/app/actions";
import { DashboardShell } from "@/components/dashboard-shell";
import { getConsultantDashboard } from "@/lib/queries";
import { requireUser } from "@/lib/session";

export const dynamic = "force-dynamic";
const statusContent = { NOT_SUBMITTED: { label: "Ainda não verificado", copy: "Solicite a análise para mostrar que sua experiência profissional foi validada.", icon: CircleAlert }, PENDING: { label: "Em análise", copy: "Sua solicitação chegou à equipe. Você receberá uma atualização quando a análise terminar.", icon: Clock3 }, VERIFIED: { label: "Experiência verificada", copy: "Seu perfil público já exibe o selo de experiência verificada.", icon: BadgeCheck }, REJECTED: { label: "Solicitação não aprovada", copy: "Você pode enviar uma nova solicitação escolhendo outra forma de comprovação.", icon: CircleAlert }, MORE_INFO_REQUIRED: { label: "Precisamos de mais informações", copy: "Envie uma nova solicitação com outra forma de comprovação.", icon: CircleAlert } } as const;
export default async function Page() { const user = await requireUser([Role.CONSULTANT]); const profile = await getConsultantDashboard(user.id); const status = profile?.verificationStatus ?? VerificationStatus.NOT_SUBMITTED; const content = statusContent[status]; const StatusIcon = content.icon; const canRequest = status !== VerificationStatus.PENDING && status !== VerificationStatus.VERIFIED;
return <DashboardShell mode="consultant" title="Perfil e verificação"><div className="profile-admin-grid"><section className="panel profile-preview-panel"><span className="eyebrow">Seu perfil público</span><h2>{profile?.headline}</h2><p>{profile?.bio}</p>{profile && <Link className="button button-dark" href={`/profissional/${profile.id}`}>Abrir perfil público <ArrowUpRight size={16}/></Link>}</section><section className={`panel verification-panel verification-${status.toLowerCase()}`} id="verificacao"><div className="verification-heading"><span className="verification-icon"><StatusIcon size={25}/></span><div><span className="eyebrow">Verificação profissional</span><h2>{content.label}</h2></div></div><p>{content.copy}</p>{canRequest && <form className="verification-form" action={submitVerificationAction}><div className="field"><label htmlFor="method">Como você prefere comprovar?</label><select className="select" id="method" name="method" defaultValue="company_email"><option value="company_email">E-mail corporativo</option><option value="employment_document">Documento de vínculo profissional</option><option value="professional_reference">Referência profissional verificável</option></select></div><div className="verification-note"><ShieldCheck size={18}/><span>A comprovação é usada somente pela equipe de análise. Nenhum documento ou contato é exibido no seu perfil público.</span></div><button className="button button-accent" type="submit">Solicitar verificação</button></form>}{status === VerificationStatus.PENDING && <div className="verification-progress"><span/><span/><span/><small>Solicitação recebida</small><small>Análise da experiência</small><small>Resultado no perfil</small></div>}{status === VerificationStatus.VERIFIED && <div className="verified-company"><Building2 size={20}/><span>O selo confirma a experiência analisada sem revelar dados privados.</span></div>}</section></div></DashboardShell>; }
