import { getPublicCompanies, getPublicProfessions, getUserById } from "@/lib/queries";
import Link from "next/link";
import { Role, VerificationStatus } from "@/lib/domain";
import { ArrowUpRight, BadgeCheck, Building2, CircleAlert, Clock3 } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { AccountDangerZone, ProfessionalProfileForm, ProfileImageForm, VerificationRequestForm } from "@/components/profile-management";
import { TwoFactorEnabled, TwoFactorSetup } from "@/components/two-factor";
import { getSupabaseTwoFactorSetup } from "@/app/actions";
import { getConsultantDashboard } from "@/lib/queries";
import { requireUser } from "@/lib/session";


export const dynamic = "force-dynamic";
const statusContent = { NOT_SUBMITTED: { label: "Ainda n verificado", copy: "Solicite a an para mostrar que sua experi profissional foi validada.", icon: CircleAlert }, PENDING: { label: "Em an", copy: "Sua solicita chegou ? equipe. Voc receber? uma atualiza quando a an terminar.", icon: Clock3 }, VERIFIED: { label: "Experi verificada", copy: "Seu perfil p j exibe o selo de experi verificada.", icon: BadgeCheck }, REJECTED: { label: "Solicita n aprovada", copy: "Voc pode enviar uma nova solicita escolhendo outra forma de comprova.", icon: CircleAlert }, MORE_INFO_REQUIRED: { label: "Precisamos de mais informa", copy: "Envie uma nova solicita com outra forma de comprova.", icon: CircleAlert } } as const;
export default async function Page() { const user = await requireUser([Role.CONSULTANT]); const [profile, companies, professions, stored] = await Promise.all([getConsultantDashboard(user.id), getPublicCompanies(), getPublicProfessions(), getUserById(user.id)]); const setup=!stored?.twoFactorEnabled?await getSupabaseTwoFactorSetup():null; const status = profile?.verificationStatus ?? VerificationStatus.NOT_SUBMITTED; const content = statusContent[status as keyof typeof statusContent] ?? statusContent.NOT_SUBMITTED; const StatusIcon = content.icon; const canRequest = status !== VerificationStatus.PENDING && status !== VerificationStatus.VERIFIED;
return <DashboardShell mode="consultant" title="Perfil e verifica"><div className="profile-management-stack"><ProfileImageForm image={profile?.user.image} name={profile?.user.name||user.name||"Pessoa"}/>{profile && <ProfessionalProfileForm profile={profile} companies={companies} professions={professions}/>}<div className="profile-admin-grid"><section className="panel profile-preview-panel"><span className="eyebrow">Seu perfil p</span><h2>{profile?.headline}</h2><p>{profile?.bio}</p>{profile && <Link className="button button-dark" href={`/profissional/${profile.id}`}>Abrir perfil p <ArrowUpRight size={16}/></Link>}</section><section className={`panel verification-panel verification-${status.toLowerCase()}`} id="verificacao"><div className="verification-heading"><span className="verification-icon"><StatusIcon size={25}/></span><div><span className="eyebrow">Verifica profissional</span><h2>{content.label}</h2></div></div><p>{content.copy}</p>{canRequest && <VerificationRequestForm/>}{status === VerificationStatus.PENDING && <div className="verification-progress"><span/><span/><span/><small>Solicita recebida</small><small>An da experi</small><small>Resultado no perfil</small></div>}{status === VerificationStatus.VERIFIED && <div className="verified-company"><Building2 size={20}/><span>O selo confirma a experi analisada sem revelar dados privados.</span></div>}</section></div>{stored?.twoFactorEnabled?<TwoFactorEnabled/>:setup && !setup.enabled?<TwoFactorSetup uri={setup.uri} factorId={setup.factorId}/>:null}<AccountDangerZone email={user.email||""}/></div></DashboardShell>; }
