ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'AWAITING_CONFIRMATION';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'DISPUTED';

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'HELD';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'RELEASED';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'DISPUTED';

ALTER TABLE "Booking"
  ADD COLUMN IF NOT EXISTS "customerConfirmedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "consultantConfirmedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "autoReleaseAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "disputedAt" TIMESTAMP(3);

ALTER TABLE "Payment"
  ADD COLUMN IF NOT EXISTS "releasedAt" TIMESTAMP(3);
