create or replace function public.get_consultant_dashboard(p_user_id text)
returns jsonb language plpgsql security definer set search_path = '' as $function$
declare v_auth uuid := auth.uid(); v_profile public."ProfessionalProfile"; v_result jsonb;
begin
  if v_auth is null or not exists (select 1 from public."User" u where u.id=p_user_id and u."auth_user_id"=v_auth and u.role='CONSULTANT'::public."Role") then raise exception 'not_authorized'; end if;
  select p.* into v_profile from public."ProfessionalProfile" p where p."userId"=p_user_id;
  if not found then return null; end if;
  select jsonb_build_object('id',v_profile.id,'userId',v_profile."userId",'headline',v_profile.headline,'bio',v_profile.bio,'publicSurname',v_profile."publicSurname",'location',v_profile.location,'region',v_profile.region,'workMode',v_profile."workMode",'seniority',v_profile.seniority,'yearsExperience',v_profile."yearsExperience",'price30Cents',v_profile."price30Cents",'price60Cents',v_profile."price60Cents",'pixKey',v_profile."pixKey",'responseHours',v_profile."responseHours",'privacyMode',v_profile."privacyMode",'pseudonym',v_profile.pseudonym,'avatarSeed',v_profile."avatarSeed",'topics',v_profile.topics,'boundaries',v_profile.boundaries,'verificationStatus',v_profile."verificationStatus",'isActive',v_profile."isActive",'createdAt',v_profile."createdAt",'updatedAt',v_profile."updatedAt",'user',(select to_jsonb(u)-'passwordHash'-'twoFactorSecret'-'twoFactorRecoveryCodes' from public."User" u where u.id=p_user_id),'privacy',(select to_jsonb(x) from public."PrivacySettings" x where x."professionalProfileId"=v_profile.id),'experiences',coalesce((select jsonb_agg(to_jsonb(x)||jsonb_build_object('company',(select to_jsonb(c) from public."Company" c where c.id=x."companyId"),'profession',(select to_jsonb(f) from public."Profession" f where f.id=x."professionId")) order by x."isCurrent" desc) from public."EmploymentExperience" x where x."professionalProfileId"=v_profile.id),'[]'::jsonb),'availability',coalesce((select jsonb_agg(to_jsonb(a) order by a."startsAt") from public."Availability" a where a."professionalProfileId"=v_profile.id and a."endsAt">now()),'[]'::jsonb),'profileViews',coalesce((select jsonb_agg(to_jsonb(v)) from public."ProfileView" v where v."professionalProfileId"=v_profile.id),'[]'::jsonb),'favorites',coalesce((select jsonb_agg(to_jsonb(f)) from public."Favorite" f where f."professionalProfileId"=v_profile.id),'[]'::jsonb),'bookings',coalesce((select jsonb_agg(to_jsonb(b)||jsonb_build_object('customer',(select jsonb_build_object('id',u.id,'name',u.name) from public."User" u where u.id=b."customerId"),'payment',(select to_jsonb(pay) from public."Payment" pay where pay."bookingId"=b.id),'conversation',(select to_jsonb(c)||jsonb_build_object('messages',coalesce((select jsonb_agg(to_jsonb(m)||jsonb_build_object('sender',(select jsonb_build_object('id',su.id,'name',su.name) from public."User" su where su.id=m."senderId")) order by m."createdAt") from public."Message" m where m."conversationId"=c.id),'[]'::jsonb)) from public."Conversation" c where c."bookingId"=b.id)) order by b."startsAt" desc) from public."Booking" b where b."professionalProfileId"=v_profile.id),'[]'::jsonb)) into v_result;
  return v_result;
end;
$function$;
