import Link from "next/link";
import { notFound } from "next/navigation";
import { BriefcaseBusiness, CalendarDays, Clock, Heart, ShieldCheck, Star } from "lucide-react";
import { toggleFavoriteAction } from "@/app/actions";
import { PublicShell } from "@/components/public-shell";
import { initials, money, publicName, shortDate } from "@/lib/format";
import { getProfessional } from "@/lib/queries";

export const dynamic = "force-dynamic";
export default async function ProfessionalPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const profile = await getProfessional(id); if (!profile) notFound();
  const name = publicName(profile); const topics = profile.topics ?? []; const experiences = profile.experiences ?? []; const boundaries = profile.boundaries ?? []; const reviews = profile.reviews ?? []; const availability = profile.availability ?? []; profile.topics = topics; profile.experiences = experiences; profile.boundaries = boundaries; profile.reviews = reviews; profile.availability = availability; const avg = reviews.length ? reviews.reduce((s,r)=>s+r.rating,0)/reviews.length : 0; const photo=profile.privacy?.showPhoto?profile.user.image:null;
  return <PublicShell><section className="profile-hero"><div className="container"><div className={`avatar${photo ? " avatar-photo" : ""}`} style={{width:120,fontSize:"2.4rem",...(photo ? {backgroundImage:`url(${photo})`}: {})}}>{photo ? null : initials(name)}</div><div className="card-meta"><span className="badge"><ShieldCheck size={13}/>{profile.verificationStatus === "VERIFIED" ? "Experiência verificada" : "Verificação em análise"}</span><span className="badge">{profile.privacyMode === "PUBLIC" ? "Perfil público" : "Identidade protegida"}</span></div><h1 className="profile-title">{name}</h1><p className="section-copy">{profile.headline}</p></div></section><section className="section"><div className="container profile-layout"><div className="grid">
    <article className="profile-main"><span className="eyebrow">Sobre a experiência</span><h2>Contexto que posso compartilhar</h2><p>{profile.bio}</p><div className="card-meta">{profile.topics.map(topic=><span className="badge" key={topic}>{topic}</span>)}</div></article>
    <article className="profile-main"><span className="eyebrow">Trajetória</span><h2>Experiência declarada</h2><ul className="detail-list">{profile.experiences.map(exp=><li key={exp.id}><div><strong>{exp.title}</strong><br/><span className="muted">{exp.profession.name} · {exp.company.name}</span></div><BriefcaseBusiness/></li>)}</ul><p className="muted">Datas exatas e histórico completo respeitam as escolhas de privacidade do consultor.</p></article>
    <article className="profile-main"><span className="eyebrow">Limites claros</span><h2>O que não entra na conversa</h2><ul>{profile.boundaries.map(item=><li key={item}>{item}</li>)}</ul></article>
    <article className="profile-main"><span className="eyebrow">{profile.reviews.length} avaliações</span><h2>Depois das conversas</h2>{profile.reviews.length ? <div className="list">{profile.reviews.map(review=><div className="list-row" key={review.id}><div><strong>{review.user.name.split(" ")[0]}</strong><p>{review.comment}</p></div><span className="rating"><Star size={14} fill="currentColor"/> {review.rating}</span></div>)}</div> : <p className="muted">Este perfil ainda não recebeu uma avaliação.</p>}</article>
  </div><aside className="booking-box"><span className="eyebrow">Conversa individual</span><h2>{money(profile.price30Cents)} <small>/ 30 min</small></h2><ul className="detail-list"><li><span><Star size={15}/> Avaliação</span><strong>{avg ? avg.toFixed(1) : "Novo"}</strong></li><li><span><Clock size={15}/> Resposta</span><strong>em até {profile.responseHours}h</strong></li><li><span><CalendarDays size={15}/> Próximo horário</span><strong>{profile.availability[0] ? shortDate(profile.availability[0].startsAt) : "A definir"}</strong></li></ul><Link className="button button-dark button-block" href={`/agendar/${profile.id}`}>Escolher horário</Link><form action={toggleFavoriteAction.bind(null, profile.id)}><button className="button button-ghost button-block" type="submit"><Heart size={16}/> Salvar perfil</button></form><p className="muted" style={{fontSize:12}}>A plataforma protege dados privados e libera a conversa somente após a confirmação do pagamento.</p></aside></div></section></PublicShell>;
}
